# permissions for end users to edit files.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: github-operator
    app.kubernetes.io/managed-by: kustomize
  name: file-editor-role
rules:
- apiGroups:
  - github.example.com
  resources:
  - files
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.example.com
  resources:
  - files/status
  verbs:
  - get
