---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - github.example.com
  resources:
  - files
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.example.com
  resources:
  - files/finalizers
  verbs:
  - update
- apiGroups:
  - github.example.com
  resources:
  - files/status
  verbs:
  - get
  - patch
  - update
