apiVersion: github.example.com/v1alpha1
kind: File
metadata:
  labels:
    app.kubernetes.io/name: github-operator
    app.kubernetes.io/managed-by: kustomize
  name: file-sample
spec:
  # TODO(user): Add fields here
