apiVersion: github.example.com/v1alpha1
kind: File
metadata:
  labels:
    app.kubernetes.io/name: github-operator
    app.kubernetes.io/managed-by: kustomize
  name: file-sample
spec:
  # The YAML content to deploy to the repository
  fileContent: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: sample-app
      labels:
        app: sample-app
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: sample-app
      template:
        metadata:
          labels:
            app: sample-app
        spec:
          containers:
          - name: nginx
            image: nginx:1.21
            ports:
            - containerPort: 80
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: sample-app-service
    spec:
      selector:
        app: sample-app
      ports:
      - port: 80
        targetPort: 80
      type: ClusterIP

  # Repository where the file should be deployed (format: owner/repo)
  repositoryURL: "myorg/my-k8s-configs"
  
  # Branch to deploy to (defaults to "main" if not specified)
  branch: "main"
  
  # Path within the repository where the file should be created
  filePath: "deployments/sample-app.yaml"
  
  # Optional commit message (defaults to auto-generated message if not specified)
  commitMessage: "Deploy sample application via Kubernetes File CRD"

---
apiVersion: github.example.com/v1alpha1
kind: File
metadata:
  labels:
    app.kubernetes.io/name: github-operator
    app.kubernetes.io/managed-by: kustomize
  name: configmap-sample
spec:
  fileContent: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: app-config
      namespace: default
    data:
      database_url: "postgresql://localhost:5432/myapp"
      log_level: "info"
      max_connections: "100"
      feature_flags: |
        {
          "enable_new_ui": true,
          "enable_beta_features": false,
          "maintenance_mode": false
        }

  repositoryURL: "myorg/my-k8s-configs"
  branch: "main"
  filePath: "config/app-configmap.yaml"
  commitMessage: "Update application configuration"
